#!/bin/bash

before=$(git status)
make precommit # might change some files
after=$(git status)

if [[ "$before" != "$after" ]]
then
  echo "Some files were changed by the formatter, please add them and commit again."
  exit 1
fi
